const UPDATE_USER = "user:UPDATE_USER";

const LOGIN_REQUEST = "user:LOGIN_REQUEST";
const LOGIN_SUCCESS = "user:LOGIN_SUCCESS";
const LOGIN_FAILURE = "user:LOGIN_FAILURE";

const LOGOUT_REQUEST = "user:LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "user:LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "user:LOGOUT_FAILURE";

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
  UPDATE_USER
};
