const UPDATE_USER = "user:UPDATE_USER";

const LOGIN_REQUEST = "user:LOGIN_REQUEST";
const LOGIN_SUCCESS = "user:LOGIN_SUCCESS";
const LOGIN_FAILURE = "user:LOGIN_FAILURE";

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  UPDATE_USER
};
