const UPDATE_USER = "user:UPDATE_USER";

const LOGIN_REQUEST = "user:LOGIN_REQUEST";
const LOGIN_SUCCESS = "user:LOGIN_SUCCESS";
const LOGIN_FAILURE = "user:LOGIN_FAILURE";

const LOGOUT_REQUEST = "user:LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "user:LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "user:LOGOUT_FAILURE";

const SIGN_UP_REQUEST = "user:SIGN_UP_REQUEST";
const SIGN_UP_SUCCESS = "user:SIGN_UP_SUCCESS";
const SIGN_UP_FAILURE = "user:SIGN_UP_FAILURE";

const VALIDATE_TOKEN_REQUEST = "user:VALIDATE_TOKEN_REQUEST";
const VALIDATE_TOKEN_SUCCESS = "user:VALIDATE_TOKEN_SUCCESS";
const VALIDATE_TOKEN_FAILURE = "user:VALIDATE_TOKEN_FAILURE";

const UPDATE_AUTH = "user:UPDATE_AUTH";

const UPDATE_TOKEN = "user:UPDATE_TOKEN";

export default {
  UPDATE_USER,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
  SIGN_UP_REQUEST,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILURE,
  VALIDATE_TOKEN_REQUEST,
  VALIDATE_TOKEN_SUCCESS,
  VALIDATE_TOKEN_FAILURE,
  UPDATE_TOKEN,
  UPDATE_AUTH
};
