export const LOAD_BEERS_REQUEST = "beers:LOAD_BEERS_REQUEST";
export const LOAD_BEERS_SUCCESS = "beers:LOAD_BEERS_SUCCESS";
export const LOAD_BEERS_FAILURE = "beers:LOAD_BEERS_FAILURE";

export const LOAD_BEER_REQUEST = "beers:LOAD_BEER_REQUEST";
export const LOAD_BEER_SUCCESS = "beers:LOAD_BEER_SUCCESS";
export const LOAD_BEER_FAILURE = "beers:LOAD_BEER_FAILURE";

export const UPDATE_BEERS = "beers:UPDATE_BEERS";
export const UPDATE_RELOAD_BEERS = "beers:UPDATE_RELOAD_BEERS";
export const UPDATE_SELECTED_BEER = "beers:UPDATE_SELECTED_BEER";
export const FILTER_BEERS = "beers:FILTER_BEERS";

export default {
  LOAD_BEERS_REQUEST,
  LOAD_BEERS_SUCCESS,
  LOAD_BEERS_FAILURE,
  LOAD_BEER_REQUEST,
  LOAD_BEER_SUCCESS,
  LOAD_BEER_FAILURE,
  UPDATE_BEERS,
  UPDATE_SELECTED_BEER,
  FILTER_BEERS,
  UPDATE_RELOAD_BEERS
};
