const LOAD_ORDERS_REQUEST = "order:LOAD_ORDERS_REQUEST";
const LOAD_ORDERS_SUCCESS = "order:LOAD_ORDERS_SUCCESS";
const LOAD_ORDERS_FAILURE = "order:LOAD_ORDERS_FAILURE";

const CREATE_ORDER_REQUEST = "order:CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "order:CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILURE = "order:CREATE_ORDER_FAILURE";

const DELETE_ORDER_REQUEST = "order:DELETE_ORDER_REQUEST";
const DELETE_ORDER_SUCCESS = "order:DELETE_ORDER_SUCCESS";
const DELETE_ORDER_FAILURE = "order:DELETE_ORDER_FAILURE";

const BUY_ORDER_REQUEST = "order:BUY_ORDER_REQUEST";
const BUY_ORDER_SUCCESS = "order:BUY_ORDER_SUCCESS";
const BUY_ORDER_FAILURE = "order:BUY_ORDER_FAILURE";

const UPDATE_ORDERS = "order:UPDATE_ORDERS";

export default {
  LOAD_ORDERS_REQUEST,
  LOAD_ORDERS_SUCCESS,
  LOAD_ORDERS_FAILURE,
  CREATE_ORDER_REQUEST,
  CREATE_ORDER_SUCCESS,
  CREATE_ORDER_FAILURE,
  DELETE_ORDER_REQUEST,
  DELETE_ORDER_SUCCESS,
  DELETE_ORDER_FAILURE,
  BUY_ORDER_REQUEST,
  BUY_ORDER_SUCCESS,
  BUY_ORDER_FAILURE,
  UPDATE_ORDERS
};
