const LOAD_PRODUCTS_REQUEST = "products:LOAD_PRODUCTS_REQUEST";
const LOAD_PRODUCTS_SUCCESS = "product:LOAD_PRODUCTS_SUCCESS";
const LOAD_PRODUCTS_FAILURE = "product:LOAD_PRODUCTS_FAILURE";

const LOAD_PRODUCT_REQUEST = "product:LOAD_PRODUCT_REQUEST";
const LOAD_PRODUCT_SUCCESS = "product:LOAD_PRODUCT_SUCCESS";
const LOAD_PRODUCT_FAILURE = "product:LOAD_PRODUCT_FAILURE";

const CREATE_PRODUCT_REQUEST = "product:CREATE_PRODUCT_REQUEST";
const CREATE_PRODUCT_SUCCESS = "product:CREATE_PRODUCT_SUCCESS";
const CREATE_PRODUCT_FAILURE = "product:CREATE_PRODUCT_FAILURE";

export default {
  LOAD_PRODUCTS_REQUEST,
  LOAD_PRODUCTS_SUCCESS,
  LOAD_PRODUCTS_FAILURE,
  LOAD_PRODUCT_REQUEST,
  LOAD_PRODUCT_SUCCESS,
  LOAD_PRODUCT_FAILURE,
  CREATE_PRODUCT_REQUEST,
  CREATE_PRODUCT_SUCCESS,
  CREATE_PRODUCT_FAILURE
};
